version: '3.10'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django_dockerization
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
   
volumes:
  data: